import os
import xml.etree.ElementTree as ElementTree

from config import *

es_systems = ElementTree.parse(es_systems_path).getroot()

ignored_systems = [
    "bios",
    "screenshots",
    "bezels",
    "update",
    "bgm",
    "gamedata",
    "mplayer",
    "351elec-web"
]

system_map = {
    "amiga": "Amiga",
    "amigacd32": "Amiga CD32",
    "amstradcpc": "Amstrad CPC",
    "arcade": "Arcade",
    "atari800": "Atari 800",
    "atari2600": "Atari 2600",
    "atari5200": "Atari 5200",
    "atari7800": "Atari 7800",
    "atarilynx": "Atari Lynx",
    "atarist": "Atari ST",
    "atomiswave": "Sammy Atomiswave",
    "wonderswan": "Bandai Wonderswan",
    "wonderswancolor": "Bandai Wonderswan Color",
    "channelf": "Fairchild Channel F",
    "coleco": "Colecovision",
    "c16": "Commodore 16 (Plus/4)",
    "c64": "Commodore 64",
    "c128": "Commodore 128",
    "vic20": "Commodore VIC-20",
    "daphne": "Daphne",
    "fbneo": "Finalburn Neo",
    "intellivision": "Mattel Intellivision",
    "mame": "Mame",
    "msx": "MSX",
    "msx2": "MSX2",
    "pc88": "NEC PC 8800",
    "pc98": "NEC PC 9800",
    "pcengine": "NEC PC Engine",
    "pcenginecd": "NEC PC Engine Cd",
    "sgfx": "NEC SuperGrafx",
    "tg16": "NEC TurboGrafx 16",
    "tg16cd": "NEC Turbografx CD",
    "nes": "Nintendo Entertainment System",
    "famicom": "Famicom",
    "fds": "Famicom Disk System",
    "gb": "Game Boy",
    "gba": "Game Boy Advance",
    "gbc": "Game Boy Color",
    "gameandwatch": "Game & Watch",
    "pokemini": "Pokémon Mini",
    "snes": "Super Nintendo",
    "sfc": "Super Famicom",
    "snesmsu1": "Super Nintendo MSU-1",
    "satellaview": "SatellaView",
    "sufami": "Bandai Sufami Turbo",
    "virtualboy": "Virtual Boy",
    "odyssey": "Magnavox Odyssey²",
    "videopac": "Philips Videopac",
    "pc": "PC (DOX x86)",
    "pico-8": "Pico-8",
    "psx": "Sony Playstation",
    "sg-1000": "Sega SG-1000",
    "sc-3000": "Sega SC-3000",
    "gamegear": "Sega Gamegear",
    "mastersystem": "Sega Master System",
    "genesis": "Sega Genesis",
    "megadrive": "Sega Mega Drive",
    "megadrive-japan": "Sega Mega Drive",
    "sega32x": "Sega 32x",
    "segacd": "Sega CD",
    "megacd": "Sega Mega CD",
    "neogeo": "SNK Neo-Geo",
    "neocd": "SNK Neo-Geo CD",
    "ngp": "SNK Neo-Geo Pocket",
    "ngpc": "SNK Neo-Geo Pocket Color",
    "supervision": "Watara Supervision",
    "megaduck": "Welback Holdings Megaduck",
    "tic-80": "Tic-80",
    "uzebox": "Uzebox",
    "vectrex": "GCE Vectrex",
    "x1": "Sharp X1",
    "x68000": "Sharp X68000",
    "zx81": "Sinclair ZX81",
    "zxspectrum": "Sinclair ZX Spectrum",
    "build": "Build Engine",
    "doom": "Doom",
    "easyrpg": "EasyRPG",
    "openbor": "OpenBOR",
    "scummvm": "Scummvm",
    "solarus": "Solarus",
    "ecwolf": "Wolfenstein 3D",
    "3do": "3DO",
    "j2me": "J2ME",
    "pcfx": "NEC PC-FX",
    "n64": "Nintendo N64",
    "nds": "Nintendo Ds",
    "naomi": "Sega Naomi",
    "dreamcast": "Sega Dreamcast",
    "saturn": "Sega Saturn",
    "psp": "Sony PSP",
    "pspminis": "Sony PSP Minis",
    "eduke": "Duke Nukem 3D",
    "ports": "Ports"
}
